### ISSUE TITLE
arbtest run() and tracing

### ISSUE THREAD

**Issue by hellertime** [matklad/arbtest#4]
I've noticed that if I define a tests as a prop and run it in arbtest, my `tracing` setup with the test-log crate does not appear when running a test like this `RUST_LOG=trace cargo test -- --nocapture`, tests that are not run within arbtest produce output just fine with the same setup.

Is there something to configure with arbtest to allow the output to be sent to stdout?

**Comment by matklad** [comment]
Hm, that's strange, I don't think we do anything more fancy than just running the test in a loop, so there shouldn't be any interference between libtest, arbtest and tracing...

**Comment by hellertime** [comment]
I will add that `println!` works fine, so maybe this has something more to do with a test-log and arbitrary interaction, but curious if others may have worked out a solution.

**Comment by matklad** [comment]
Arbtest itself just prints to stderr:

https://github.com/matklad/arbtest/blob/230943946f225ed6c3b0c74db4089d6383523c40/src/lib.rs#L255

**Comment by hellertime** [comment]
I think its OK to close this issue. I'll have to revisit how my code is operating, as I made up a small test case, and I can get output to appear:

`Cargo.toml`
```toml
[package]
name = "tracing_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
arbitrary = { version = "1", features = ["derive"] }
arbtest = "0.2.0"
test-log = { version = "0.2", default-features = false, features = ["trace"] }
tracing = {version = "0.1", default-features = false}
tracing-subscriber = {version = "0.3", default-features = false, features = ["env-filter", "fmt"]}
```

`main.rs`
```rust
fn main() {
}

#[cfg(test)]
mod tests {
    use arbitrary::Unstructured;
    use test_log::test;

    #[test]
    fn foobar() {
        fn prop(_u: &mut Unstructured<'_>) -> arbitrary::Result<()> {
            tracing::trace!("Oh pop a dah!");
            Ok(())
        }
        arbtest::builder().run(prop);
    }
}
```
